name: CI

on:
  push:
    branches: [ "master" ]
  pull_request:
  workflow_dispatch:

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        cc:
        - gcc
        - clang
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
      with:
        submodules: recursive

    - name: make test
      run: make test CC=${{ matrix.cc }}
